### ISSUE TITLE
Does not work on Firefox mobile

### ISSUE THREAD

**Issue by precu** [paulirish/matchMedia.js#57]
Hello !

firstable thank you for your tremendous job, it really help.

Unfortunatly it seems that firefox mobile doesn't catch the width and height the same way the other browsers do.

does anybody have the same problem ?

thanks for helping !

**Comment by vyorkin** [comment]
@precu did you resolve this issue and is it still relevant?

**Comment by paulirish** [comment]
i presume this is solved now. FF mobile surely doesnt need the polyfill.
