### ISSUE TITLE
Add minified sources and use common bower directory structure

### ISSUE THREAD

**Issue by ste93cry** [paulirish/matchMedia.js#63]
It would be nice if you can provide a `dist` folder with all the sources, uncompressed and compressed. This folder structure is common in many libraries out of here and simplify the deployment because it's somehow a standardized folder name and user does not have to care about minifying the source.

**Comment by codedbypaul** [comment]
Were you able to get this working with mainBowerFiles? I tried overriding but it still doesn't pick them up.

**Comment by ste93cry** [comment]
sorry, I didn't try that

**Comment by ste93cry** [comment]
@paulirish any news about this issue?

**Comment by paulirish** [comment]
no plans to do this.
