### ISSUE TITLE
Support fetching DPI

### ISSUE THREAD

**Issue by zeeshanjan82** [paulirish/matchMedia.js#65]
I wish there could be some way I could get the DPI of the screen, I have a requirement where the user will define the dimensions of the buttons on my web page in cm/mm and I need to display them in these dimensions but as far as I have read I need to have the DPI of the screen in order to convert cm/mm into pixels.

**Comment by zeeshanjan82** [comment]
https://github.com/LeaVerou/dpi/issues/132

**Comment by benschwarz** [comment]
If a regular media query can't do it, then matchMedia won't either — matchMedia serves only as a polyfill to browsers that do not support the `matchMedia` JS API.
