### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by Alex-Vaduva** [paulirish/matchMedia.js#77]
In matchMedia.js, the license is: "Dual MIT/BSD license".
What does that mean? Can I choose between MIT or BSD? Or do both licenses apply?
Also to which BSD are you referring? BSD 2, 3 or 4 clause?

Thanks,
Alex

**Comment by Alex-Vaduva** [comment]
Is there any update on this issues?

**Comment by paulirish** [comment]
we nuked the BSD dual a while ago

it's only MIT.


:)
