### ISSUE TITLE
PS Vita fails matching

### ISSUE THREAD

**Issue by mmespn** [paulirish/matchMedia.js#8]
The Playstation Vita Silk browser ( Silk 3.2, Webkit 531.22.8) unreliably matches media queries.

The test element div's offsetWidth is reported as 41px instead of the expected 42px.

This occurs when calling matchMedia from within the head or body, though curiously it appears to pass/fail for only one or the other, and alternates which passes and fails between each page load.

Test case: https://gist.github.com/1894191

**Comment by paulirish** [comment]
i think this browser is dead now. :)

closing
