### ISSUE TITLE
The package published to npm has legacy code

### ISSUE THREAD

**Issue by TxHawks** [paulirish/matchMedia.js#82]
The package published to npm does not contain the check added in #76, which makes it fail in JSDOM

**Comment by joaovieira** [comment]
Just came here for the same. Need #76 for the same Jest setup reason. Could you publish a new version to NPM? Thanks

**Comment by TxHawks** [comment]
Until this is resolved, I've forked the repository and published it to npm.

You can install it using 
```sh 
npm iinstall -D @txhawks/matchmedia-polyfill
```

or

```sh
yarn -D @txhawks/matchmedia-polyfill
```

**Comment by unindented** [comment]
@paulirish any chance of seeing a new version of this package published to npm?

**Comment by paulirish** [comment]
thanks for the poke. tagged as 0.3.1 and publishing to NPM now.

**Comment by ljharb** [comment]
@paulirish i'm still not seeing it on npm; also it doesn't appear that you have publish access.

**Comment by paulirish** [comment]
@ljharb yup. seems to be a replication issue at NPM. something like https://github.com/npm/npm/issues/6308 ?

https://www.npmjs.com/settings/paulirish/packages now shows `matchmedia-polyfill`, but https://www.npmjs.com/package/matchmedia-polyfill doesn't have me. (also `npm info` remains stale.) 

i'll ping this issue when 0.3.1 is definitely published.

**Comment by paulirish** [comment]
0.3.1 is published.

![image](https://user-images.githubusercontent.com/39191/41379581-3775e02a-6f17-11e8-8d72-96c9e1ecdb9a.png)

**Comment by ljharb** [comment]
@paulirish ah, thanks. i've gotten that caching issue fixed wrt owners by emailing support@npmjs.com; as for the version, I'm now seeing it show up!
